/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as SpotsIndexRouteImport } from './routes/spots.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminSpotsRouteImport } from './routes/admin.spots'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminJournalRouteImport } from './routes/admin.journal'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as SpotsContinentIndexRouteImport } from './routes/spots.$continent.index'
import { Route as TripsThemeSlugRouteImport } from './routes/trips.theme.$slug'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as SpotsContinentRegionIndexRouteImport } from './routes/spots.$continent.$region.index'
import { Route as SpotsContinentRegionSpotRouteImport } from './routes/spots.$continent.$region.$spot'

const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsIndexRoute = SpotsIndexRouteImport.update({
  id: '/spots/',
  path: '/spots/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/admin/trips',
  path: '/admin/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpotsRoute = AdminSpotsRouteImport.update({
  id: '/admin/spots',
  path: '/admin/spots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalRoute = AdminJournalRouteImport.update({
  id: '/admin/journal',
  path: '/admin/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsContinentIndexRoute = SpotsContinentIndexRouteImport.update({
  id: '/spots/$continent/',
  path: '/spots/$continent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsThemeSlugRoute = TripsThemeSlugRouteImport.update({
  id: '/trips/theme/$slug',
  path: '/trips/theme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsContinentRegionIndexRoute =
  SpotsContinentRegionIndexRouteImport.update({
    id: '/spots/$continent/$region/',
    path: '/spots/$continent/$region/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpotsContinentRegionSpotRoute =
  SpotsContinentRegionSpotRouteImport.update({
    id: '/spots/$continent/$region/$spot',
    path: '/spots/$continent/$region/$spot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal': typeof JournalRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/trips/theme/$slug': typeof TripsThemeSlugRoute
  '/spots/$continent/': typeof SpotsContinentIndexRoute
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
  '/spots/$continent/$region/': typeof SpotsContinentRegionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal': typeof JournalRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin': typeof AdminIndexRoute
  '/spots': typeof SpotsIndexRoute
  '/trips': typeof TripsIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/trips/theme/$slug': typeof TripsThemeSlugRoute
  '/spots/$continent': typeof SpotsContinentIndexRoute
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
  '/spots/$continent/$region': typeof SpotsContinentRegionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal': typeof JournalRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spots': typeof AdminSpotsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/spots/': typeof SpotsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/trips/theme/$slug': typeof TripsThemeSlugRoute
  '/spots/$continent/': typeof SpotsContinentIndexRoute
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
  '/spots/$continent/$region/': typeof SpotsContinentRegionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journal'
    | '/admin/about'
    | '/admin/homepage'
    | '/admin/journal'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/spots'
    | '/admin/trips'
    | '/journal/$slug'
    | '/trips/$id'
    | '/admin/'
    | '/spots/'
    | '/trips/'
    | '/api/public/leads'
    | '/trips/theme/$slug'
    | '/spots/$continent/'
    | '/spots/$continent/$region/$spot'
    | '/spots/$continent/$region/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/journal'
    | '/admin/about'
    | '/admin/homepage'
    | '/admin/journal'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/spots'
    | '/admin/trips'
    | '/journal/$slug'
    | '/trips/$id'
    | '/admin'
    | '/spots'
    | '/trips'
    | '/api/public/leads'
    | '/trips/theme/$slug'
    | '/spots/$continent'
    | '/spots/$continent/$region/$spot'
    | '/spots/$continent/$region'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/journal'
    | '/admin/about'
    | '/admin/homepage'
    | '/admin/journal'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/spots'
    | '/admin/trips'
    | '/journal/$slug'
    | '/trips/$id'
    | '/admin/'
    | '/spots/'
    | '/trips/'
    | '/api/public/leads'
    | '/trips/theme/$slug'
    | '/spots/$continent/'
    | '/spots/$continent/$region/$spot'
    | '/spots/$continent/$region/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JournalRoute: typeof JournalRouteWithChildren
  AdminAboutRoute: typeof AdminAboutRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminJournalRoute: typeof AdminJournalRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpotsRoute: typeof AdminSpotsRoute
  AdminTripsRoute: typeof AdminTripsRoute
  TripsIdRoute: typeof TripsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SpotsIndexRoute: typeof SpotsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  TripsThemeSlugRoute: typeof TripsThemeSlugRoute
  SpotsContinentIndexRoute: typeof SpotsContinentIndexRoute
  SpotsContinentRegionSpotRoute: typeof SpotsContinentRegionSpotRoute
  SpotsContinentRegionIndexRoute: typeof SpotsContinentRegionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/': {
      id: '/spots/'
      path: '/spots'
      fullPath: '/spots/'
      preLoaderRoute: typeof SpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/admin/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spots': {
      id: '/admin/spots'
      path: '/admin/spots'
      fullPath: '/admin/spots'
      preLoaderRoute: typeof AdminSpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/admin/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$continent/': {
      id: '/spots/$continent/'
      path: '/spots/$continent'
      fullPath: '/spots/$continent/'
      preLoaderRoute: typeof SpotsContinentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/theme/$slug': {
      id: '/trips/theme/$slug'
      path: '/trips/theme/$slug'
      fullPath: '/trips/theme/$slug'
      preLoaderRoute: typeof TripsThemeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$continent/$region/': {
      id: '/spots/$continent/$region/'
      path: '/spots/$continent/$region'
      fullPath: '/spots/$continent/$region/'
      preLoaderRoute: typeof SpotsContinentRegionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$continent/$region/$spot': {
      id: '/spots/$continent/$region/$spot'
      path: '/spots/$continent/$region/$spot'
      fullPath: '/spots/$continent/$region/$spot'
      preLoaderRoute: typeof SpotsContinentRegionSpotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JournalRoute: JournalRouteWithChildren,
  AdminAboutRoute: AdminAboutRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminJournalRoute: AdminJournalRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpotsRoute: AdminSpotsRoute,
  AdminTripsRoute: AdminTripsRoute,
  TripsIdRoute: TripsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SpotsIndexRoute: SpotsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  TripsThemeSlugRoute: TripsThemeSlugRoute,
  SpotsContinentIndexRoute: SpotsContinentIndexRoute,
  SpotsContinentRegionSpotRoute: SpotsContinentRegionSpotRoute,
  SpotsContinentRegionIndexRoute: SpotsContinentRegionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
