/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotsIndexRouteImport } from './routes/spots.index'
import { Route as SpotsContinentRouteImport } from './routes/spots.$continent'
import { Route as SpotsContinentRegionRouteImport } from './routes/spots.$continent.$region'
import { Route as SpotsContinentRegionSpotRouteImport } from './routes/spots.$continent.$region.$spot'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsIndexRoute = SpotsIndexRouteImport.update({
  id: '/spots/',
  path: '/spots/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsContinentRoute = SpotsContinentRouteImport.update({
  id: '/spots/$continent',
  path: '/spots/$continent',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsContinentRegionRoute = SpotsContinentRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => SpotsContinentRoute,
} as any)
const SpotsContinentRegionSpotRoute =
  SpotsContinentRegionSpotRouteImport.update({
    id: '/$spot',
    path: '/$spot',
    getParentRoute: () => SpotsContinentRegionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/spots/$continent': typeof SpotsContinentRouteWithChildren
  '/spots/': typeof SpotsIndexRoute
  '/spots/$continent/$region': typeof SpotsContinentRegionRouteWithChildren
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/spots/$continent': typeof SpotsContinentRouteWithChildren
  '/spots': typeof SpotsIndexRoute
  '/spots/$continent/$region': typeof SpotsContinentRegionRouteWithChildren
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/spots/$continent': typeof SpotsContinentRouteWithChildren
  '/spots/': typeof SpotsIndexRoute
  '/spots/$continent/$region': typeof SpotsContinentRegionRouteWithChildren
  '/spots/$continent/$region/$spot': typeof SpotsContinentRegionSpotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/spots/$continent'
    | '/spots/'
    | '/spots/$continent/$region'
    | '/spots/$continent/$region/$spot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/spots/$continent'
    | '/spots'
    | '/spots/$continent/$region'
    | '/spots/$continent/$region/$spot'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/spots/$continent'
    | '/spots/'
    | '/spots/$continent/$region'
    | '/spots/$continent/$region/$spot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SpotsContinentRoute: typeof SpotsContinentRouteWithChildren
  SpotsIndexRoute: typeof SpotsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/': {
      id: '/spots/'
      path: '/spots'
      fullPath: '/spots/'
      preLoaderRoute: typeof SpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$continent': {
      id: '/spots/$continent'
      path: '/spots/$continent'
      fullPath: '/spots/$continent'
      preLoaderRoute: typeof SpotsContinentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$continent/$region': {
      id: '/spots/$continent/$region'
      path: '/$region'
      fullPath: '/spots/$continent/$region'
      preLoaderRoute: typeof SpotsContinentRegionRouteImport
      parentRoute: typeof SpotsContinentRoute
    }
    '/spots/$continent/$region/$spot': {
      id: '/spots/$continent/$region/$spot'
      path: '/$spot'
      fullPath: '/spots/$continent/$region/$spot'
      preLoaderRoute: typeof SpotsContinentRegionSpotRouteImport
      parentRoute: typeof SpotsContinentRegionRoute
    }
  }
}

interface SpotsContinentRegionRouteChildren {
  SpotsContinentRegionSpotRoute: typeof SpotsContinentRegionSpotRoute
}

const SpotsContinentRegionRouteChildren: SpotsContinentRegionRouteChildren = {
  SpotsContinentRegionSpotRoute: SpotsContinentRegionSpotRoute,
}

const SpotsContinentRegionRouteWithChildren =
  SpotsContinentRegionRoute._addFileChildren(SpotsContinentRegionRouteChildren)

interface SpotsContinentRouteChildren {
  SpotsContinentRegionRoute: typeof SpotsContinentRegionRouteWithChildren
}

const SpotsContinentRouteChildren: SpotsContinentRouteChildren = {
  SpotsContinentRegionRoute: SpotsContinentRegionRouteWithChildren,
}

const SpotsContinentRouteWithChildren = SpotsContinentRoute._addFileChildren(
  SpotsContinentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SpotsContinentRoute: SpotsContinentRouteWithChildren,
  SpotsIndexRoute: SpotsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
